version: 2.1
orbs:
  r-packages: displayr/r-packages@dev:d8a2f5e7002b7c50b7ca5d353256332c1ff818da
parameters:
  trigger-message:
    type: string
    default: ""
  remote-deps:
    type: string
    default: ""
  plugins-branch:
    type: string
    default: ""
  triggered-packages:
    type: string
    default: ""
  executor:
    type: enum
    enum: [nightly, rocker, machine]
    default: nightly
  save-snapshots:
    type: boolean
    default: true    

workflows:
  build-and-check-R-package:
    jobs:
      - r-packages/build-and-check-package:
          executor: << pipeline.parameters.executor >>
          name: BuildAndCheckPackage
          context:
            - rviz_packages
          remote-deps: << pipeline.parameters.remote-deps >>
          separate-test-job: false
          save-snapshots: << pipeline.parameters.save-snapshots >>
      - r-packages/deploy-package:
          executor: << pipeline.parameters.executor >>
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          filters:
            branches:
              only:
                - master
      - r-packages/trigger-revdeps:
          executor: << pipeline.parameters.executor >>
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          remote-deps: << pipeline.parameters.remote-deps >>
          plugins-branch: << pipeline.parameters.plugins-branch >>
          trigger-message: << pipeline.parameters.trigger-message >>
          triggered-packages: << pipeline.parameters.triggered-packages >>

